In [1]:
import pandas as pd

In [3]:
mvps = pd.read_csv("C:/Prog/nbamvp/CSVs/mvps.csv")

In [5]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,8,9,Stephen Curry,34,GSW,0.0,5.0,1000,0.005,56,...,6.1,6.3,0.9,0.4,0.493,0.427,0.915,7.8,0.192,2023
495,9,10,Jimmy Butler,33,MIA,0.0,3.0,1000,0.003,64,...,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277,2023
496,10,11,De'Aaron Fox,25,SAC,0.0,2.0,1000,0.002,73,...,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146,2023
497,11,12T,Jalen Brunson,26,NYK,0.0,1.0,1000,0.001,68,...,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175,2023
498,12,12T,Ja Morant,23,MEM,0.0,1.0,1000,0.001,61,...,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148,2023

In [5]:
mvps = mvps[['Player', 'Year', 'Pts Won', 'Pts Max', 'Share']]

In [9]:
mvps.head()

            Player  Year  Pts Won  Pts Max  Share
0   Michael Jordan  1991    891.0      960  0.928
1    Magic Johnson  1991    497.0      960  0.518
2   David Robinson  1991    476.0      960  0.496
3  Charles Barkley  1991    222.0      960  0.231
4      Karl Malone  1991    142.0      960  0.148

In [7]:
players = pd.read_csv("C:/Prog/nbamvp/CSVs/players.csv")

In [13]:
players.head()

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [9]:
del players['Unnamed: 0']
del players['Rk']

In [11]:
players["Player"] = players["Player"].str.replace("*","", regex=False)

In [13]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "Tot"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

In [15]:
players = players.groupby(["Player", "Year"]).apply(single_row)

In [25]:
players.head()

                          Player Pos Age   Tm   G  GS    MP   FG   FGA   FG%  \
Player     Year
A.C. Green 1991 164   A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6  .476
           1992 633   A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8  .476
           1993 1092  A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6  .537
           1994 1579  A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3  .502
           1995 2067  A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5  .504

                      ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Year
Player     Year       ...
A.C. Green 1991 164   ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4   9.1  1991
           1992 633   ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7  13.6  1992
           1993 1092  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8  12.8  1993
           1994 1579  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7  14.7  1994
           1995 2067  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8  11.2  1995

[5 rows x 30 columns]

In [17]:
# There is a multi level index now, so we drop 2
players.index = players.index.droplevel()
players.index = players.index.droplevel()

In [19]:
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
633,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1092,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1579,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
2067,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995

In [21]:
combined_data = players.merge(mvps, how="outer", on=["Player", "Year"])

In [23]:
combined_data.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [25]:
# The players who didnt score any points in the mvp voting will have NaN values in that column, so we replace the NaNs with zeros
combined_data[["Pts Won", "Pts Max", "Share"]] = combined_data[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [27]:
combined_data[combined_data["Pts Won"] == 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13478,Žarko Čabarkapa,PF,24,GSW,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,0.0,0.0,0.0
13479,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
13480,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
13481,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
13482,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [31]:
teams = pd.read_csv("C:/Prog/nbamvp/CSVs/teams.csv")

In [33]:
teams = teams[~teams["W"].str.contains("Division")].copy()

In [35]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics*
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks*
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets*

In [37]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [39]:
nicknames = {}

with open("C:/Prog/nbamvp/CSVs/nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [41]:
combined_data["Team"] = combined_data["Tm"].map(nicknames)

In [43]:
stats = combined_data.merge(teams, how="outer", on=["Team", "Year"])

In [45]:
del stats["Unnamed: 0"]

In [47]:
stats = stats.apply(pd.to_numeric, errors="ignore")

In [49]:
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [69]:
# Why is GB object? because of a '-' which indicates the team is 0 games behind
# Replacing the - with a 0

In [71]:
stats["GB"].unique()

array(['5.0', '14.0', '23.0', '7.0', '—', '42.0', '18.0', '6.0', '24.0',
       '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0', '19.0',
       '3.0', '1.0', '13.0', '15.0', '9.0', '2.0', '35.0', '20.0', '11.0',
       '16.0', '41.0', '12.0', '10.0', '30.0', '34.0', '4.0', '1.5',
       '22.0', '51.0', '39.0', '18.5', '31.0', '48.0', '40.0', '17.0',
       '46.0', '10.5', '32.0', '38.0', '27.0', '33.0', '50.0', '43.0',
       '45.0', '25.5', '36.0', '3.5', '20.5', '11.5', '44.0', '52.0',
       '56.0', '2.5', '12.5', '32.5', '21.5', '4.5', '47.0', '22.5', nan],
      dtype=object)

In [51]:
stats["GB"] = pd.to_numeric(stats["GB"].str.replace("—","0"))

In [75]:
stats = stats.apply(pd.to_numeric, errors="ignore")

In [77]:
stats["GB"].unique()

array([ 5. , 14. , 23. ,  7. ,  0. , 42. , 18. ,  6. , 24. , 26. , 37. ,
       29. , 21. , 28. , 25. ,  8. , 19. ,  3. ,  1. , 13. , 15. ,  9. ,
        2. , 35. , 20. , 11. , 16. , 41. , 12. , 10. , 30. , 34. ,  4. ,
        1.5, 22. , 51. , 39. , 18.5, 31. , 48. , 40. , 17. , 46. , 10.5,
       32. , 38. , 27. , 33. , 50. , 43. , 45. , 25.5, 36. ,  3.5, 20.5,
       11.5, 44. , 52. , 56. ,  2.5, 12.5, 32.5, 21.5,  4.5, 47. , 22.5,
        nan])

In [53]:
stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [81]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27.0,LAL,82.0,21.0,26.4,3.1,6.6,0.476,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29.0,LAL,82.0,82.0,32.1,6.1,12.8,0.477,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22.0,LAL,52.0,0.0,7.3,1.1,2.4,0.455,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25.0,LAL,26.0,0.0,4.2,0.7,1.9,0.340,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29.0,LAL,78.0,74.0,38.6,9.2,18.7,0.492,...,0.0,0.0,Los Angeles Lakers,58.0,24.0,0.707,5.0,106.3,99.6,6.73

In [55]:
stats.to_csv("C:/Prog/nbamvp/CSVs/player_mvp_stats.csv")